/*
 HTML5 Parallax Slider
 Version: 1.0.0
 (c) 2013 DMXzone.com
 @build 10-01-2013 11:49:13
*/
(function(c){function h(a,b){this.element=c(a);this.options=c.extend({},f,b);this._defaults=f;this._name=g;this.init()}var g="dmxParallaxSlider",f={design:"default",orientation:"horizontal",duration:1500,autoPlay:!0,autoWait:5E3,startSlide:0,preloadImages:!0,preloadTimeout:2E3,directionNav:!0,controlNav:!0,keyboardNav:!0,pauseOnHover:!0,onChange:null};h.prototype={init:function(){function a(){for(var a="",c=0;c<b._slides.length;c++)a+="<a"+(c==b.currentSlide?' class="'+b._name+'Current"':"")+' rel="'+
c+'">'+(c+1)+"</a>";return a}var b=this;this._slides=this.element.children();this._width=this.width();this._height=this.height();this.nextSlide=this.oldSlide=this.currentSlide=this.options.startSlide;this.totalSlides=this._slides.length;this._isAnimating=!1;this._timer=0;this._state="none";this.container=c("<div></div>").addClass(this._name+"Container "+this._name+"-"+this.options.design).css({position:"relative",zIndex:0,display:"inline-block"});this.element.css("overflow","hidden").wrap(this.container);
this.container=this.element.parent();this.container.append('<div class="'+this._name+'Nav"></div>');"static"==this.element.css("position")&&this.element.css("position","relative");this._slides.css({position:"absolute",width:"100%",height:"100%",overflow:"hidden"}).hide();this._slides.children("."+this._name+"Element, [data-speed]").css("position","absolute");this._slides.children().on({show:function(){c(this).data("onshow")&&(new Function(b._parse(c(this).data("onshow")))).call(b)},hide:function(){c(this).data("onhide")&&
(new Function(b._parse(c(this).data("onhide")))).call(b)}});c.support.transition&&this._slides.css("transition",this._transition(this.options.duration,0));if(this.options.keyboardNav)this.element.attr("tabindex","0").on({focus:this.pause.bind(this),blur:this.cont.bind(this),keydown:this._keyEvent.bind(this)});if(this.options.pauseOnHover)this.element.on({mouseenter:this.pause.bind(this),mouseleave:this.cont.bind(this)});this.options.directionNav&&(this.container.find("."+this._name+"Nav").append('<div class="'+
this._name+'DirectionNav"><a class="'+this._name+'PrevNav">Prev</a><a class="'+this._name+'NextNav">Next</a></div>'),this.container.on({swiperight:this.prev.bind(this),swipeleft:this.next.bind(this)}),this.container.find("."+this._name+"PrevNav").on({click:this.prev.bind(this)}),this.container.find("."+this._name+"NextNav").on({click:this.next.bind(this)}));this.options.controlNav&&(this.container.find("."+this._name+"Nav").append('<div class="'+this._name+'ControlNav">'+a()+"</div>"),this.container.find("."+
this._name+"ControlNav > a").on({click:function(){b.jump(this.rel)}}));this.element.on({change:this._changeEvent.bind(this)});this.options.preloadImages?(this.element.addClass(this._name+"Loading"),this._preload().done(function(){b.element.removeClass(b._name+"Loading");b.start()}).fail(function(){alert("Not all images where loaded!");b.start()})):this.start()},width:function(){return this.element.width()},height:function(){return this.element.height()},start:function(){this._slides.eq(this.currentSlide).show().children().each(function(){c(this).trigger("show",
this)});this.options.autoPlay&&this.play()},prev:function(){this.nextSlide=this.currentSlide-1;0>this.nextSlide&&(this.nextSlide=this.totalSlides-1);this.animate(-1)},next:function(){this.nextSlide=this.currentSlide+1;this.nextSlide>=this.totalSlides&&(this.nextSlide=0);this.animate(1)},jump:function(a){a!=this.currentSlide&&(0<=a&&a<this.totalSlides)&&(this.nextSlide=+a,this.animate(this.currentSlide<this.nextSlide?1:-1))},play:function(){"playing"!=this._state&&(this._state="playing",this._timer=
setTimeout(this.next.bind(this),this.options.autoWait))},pause:function(){"playing"==this._state&&(this._state="paused",clearTimeout(this._timer))},cont:function(){"paused"==this._state&&this.play()},stop:function(){this._state="";clearTimeout(this._timer)},animate:function(a){if(!this._isAnimating){clearTimeout(this._timer);var b=this,d=this._slides.eq(this.currentSlide),e=this._slides.eq(this.nextSlide);this._isAnimating=!0;c.support.transition?(d.css("transform",this._translate(-a*this._distance())).one(c.support.transitionEnd,
function(){d.hideSlide();b._isAnimating=!1}).children("."+this._name+"Element, [data-speed]").each(function(){var d=b._slideOptions(this),e=this;setTimeout(function(){c(e).trigger("hide",e)});c(this).css("transition",b._transition(d.out.duration,d.out.delay)).css("transform",b._translate(-a*-d.lvl*(-b.width()/10)))}),e.css("transform",this._translate(a*this._distance())).showSlide().css("transform",this._translate(0)).one(c.support.transitionEnd,function(){"playing"==b._state&&(b._timer=setTimeout(b.next.bind(b),
b.options.autoWait))}).children("."+this._name+"Element, [data-speed]").each(function(){var d=b._slideOptions(this);c(this).hideSlide().css("transform",b._translate(a*-d.lvl*(-b.width()/10))).showSlide().css("transition",b._transition(d.inn.duration,d.inn.delay)).css("transform",b._translate(0)).one(c.support.transitionEnd,function(){c(this).trigger("show",this)})})):(d.animate(this._position(-a*this._distance()),{duration:this.options.duration,complete:function(){d.hide();b._isAnimating=!1}}).children("."+
this._name+"Element, [data-speed]").each(function(){var d=b._slideOptions(this),e=this;setTimeout(function(){c(e).trigger("hide",e)});c(this).delay(d.out.delay).animate(b._position(-a*-d.lvl*(-b.width()/10)),{duration:d.out.duration})}),e.css(this._position(a*this._distance())).show().animate(this._position(0),{duration:this.options.duration,complete:function(){"playing"==b._state&&(b._timer=setTimeout(b.next.bind(b),b.options.autoWait))}}).children("."+this._name+"Element, [data-speed]").each(function(){var d=
b._slideOptions(this);c(this).css(b._position(a*-d.lvl*(-b.width()/10))).delay(d.inn.delay).animate(b._position(0),{duration:d.inn.duration,complete:function(){c(this).trigger("show",this)}})}));this.oldSlide=this.currentSlide;this.currentSlide=this.nextSlide;c(this.element).trigger("change",this)}},_parse:function(a){return a.replace(/##(new)?Index##/gi,this.currentSlide).replace(/##(new)?Slide##/gi,this.currentSlide+1).replace(/##oldIndex##/gi,this.oldSlide).replace(/##oldSlide##/gi,this.oldSlide+
1)},_preload:function(){function a(a){return c.Deferred(function(e){var f=new Image,g=!1;c(f).load(function(){g=!0;e.resolve()});f.src=a;setTimeout(function(){g||e.reject()},b.options.preloadTimeout)}).promise()}var b=this;return c.Deferred(function(d){var e=[];b.element.find("img").each(function(){e.push(a(this.src))});c.when.apply(null,e).done(d.resolve).fail(d.reject)}).promise()},_keyEvent:function(a){switch(a.which){case 37:case 38:a.preventDefault();this.prev();break;case 39:case 40:a.preventDefault(),
this.next()}49<=a.which&&57>=a.which&&this.jump(a.which-49)},_changeEvent:function(){this.options.controlNav&&this.container.find("."+this._name+"ControlNav > a").removeClass(this._name+"Current").eq(this.currentSlide).addClass(this._name+"Current");this.options.onChange&&("string"==typeof this.options.onChange?(new Function(this._parse(this.options.onChange))).call(this):this.options.onChange.call(this))},_slideOptions:function(a){a=c(a);return{lvl:a.data("speed")||a.css("z-index")||0,inn:{delay:parseInt(a.data("delayin"))||
parseInt(a.data("delay"))||0,duration:parseInt(a.data("durationin"))||parseInt(a.data("duration"))||this.options.duration},out:{delay:parseInt(a.data("delayout"))||parseInt(a.data("delay"))||0,duration:parseInt(a.data("durationout"))||parseInt(a.data("duration"))||this.options.duration}}},_transition:function(a,b){var d=c.support.transform;0==d.indexOf("ms")&&(d="-"+d);return d.replace(/([A-Z])/g,"-$1").toLowerCase()+" "+a+"ms ease-in-out "+b+"ms"},_distance:function(){return"vertical"==this.options.orientation?
this.height():this.width()},_translate:function(a){return"vertical"==this.options.orientation?"translateY("+a+"px)":"translateX("+a+"px)"},_position:function(a){return"vertical"==this.options.orientation?{marginTop:a}:{marginLeft:a}}};c.fn.extend({showSlide:function(){return this.each(function(){this.style.display="block";this.offsetWidth})},hideSlide:function(){return this.each(function(){this.style.display="none";this.offsetWidth})}});c.fn[g]=function(a){var b=Array.prototype.slice.call(arguments);
return this.each(function(){var d=c.data(this,g);"string"==typeof a?d&&d[a]&&d[a].apply(d,b.slice(1)):d||c.data(this,g,new h(this,a))})};Function.prototype.bind||(Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice.call(arguments,1),c=this,e=function(){},f=function(){return c.apply(this instanceof e&&a?this:a,b.concat(Array.prototype.slice.call(arguments)))};e.prototype=
this.prototype;f.prototype=new e;return f})})(jQuery,window,document);
(function(c,h,g){c.event.special.swipe={scrollSupressionThreshold:30,durationThreshold:1E3,horizontalDistanceThreshold:30,verticalDistanceThreshold:75,setup:function(){var f=c(this);f.bind("touchstart",function(a){function b(a){if(d){var b=a.originalEvent.touches[0];e={time:(new Date).getTime(),coords:[b.pageX,b.pageY]};Math.abs(d.coords[0]-e.coords[0])>c.event.special.swipe.scrollSupressionThreshold&&a.preventDefault()}}var a=a.originalEvent.touches[0],d={time:(new Date).getTime(),coords:[a.pageX,
a.pageY],origin:c(event.target)},e;f.on("touchmove",b).one("touchend",function(){f.unbind("touchmove",b);d&&e&&(e.time-d.time<c.event.special.swipe.durationThreshold&&(Math.abs(d.coords[0]-e.coords[0])>c.event.special.swipe.horizontalDistanceThreshold&&Math.abs(d.coords[1]-e.coords[1])<c.event.special.swipe.verticalDistanceThreshold)&&d.origin.trigger("swipe").trigger(d.coords[0]>e.coords[0]?"swipeleft":"swiperight"),d=e=g)})})}};c.each({swipeleft:"swipe",swiperight:"swipe"},function(f,a){c.event.special[f]=
{setup:function(){c(this).on(a,c.noop)}}});c.each(["swipe","swipeleft","swiperight"],function(f,a){c.fn[a]=function(b){return b?this.on(a,b):this.trigger(a)};c.attrFn&&(c.attrFn[a]=!0)})})(jQuery,this);
(function(c){function h(g){var f,a,b,d=g.charAt(0).toUpperCase()+g.slice(1),e=["Moz","Webkit","O","ms"],h=document.createElement("div");if(g in h.style)b=g;else for(var i=0;i<e.length;i++)if(a=e[i]+d,a in h.style){b=a;break}(f=c.support[g]=b)&&f!==g&&(c.cssHooks[g]={get:function(a){return c.css(a,f)},set:function(a,b){a.style[f]=b}})}if(!c.cssHooks)throw"jQuery 1.4.3+ is needed for this plugin to work";h("transition");h("transform");c.support.transitionEnd={MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",
WebkitTransition:"webkitTransitionEnd",msTransition:"MSTransitionEnd",transition:"transitionend"}[c.support.transition]})(jQuery);
