/*
 Sliding Panels
 Version: 1.0.8
 (c) 2012 DMXzone.com
 @build 13-11-2012 14:58:55
*/
(function(b){var V={fast:0.9,normal:0.95,slow:0.97},W={fast:200,normal:400,slow:600};b.fn.dmxSlidingPanels=function(n){return this.each(function(){n=n||{};null!=n.deceleration&&(n.friction=n.deceleration);null!=n.scrollSpeed&&(n.transitionDuration=n.scrollSpeed);b.extend(this,new b.dmxSlidingPanels(this,n))})};b.dmxSlidingPanels=function(n,X){function L(){q=e.width();f=e.height();d.autoHeight&&(f=e.parent().innerHeight(),e.siblings().each(function(){f-=b(this).outerHeight(!0)}),f-=e.outerHeight(!0)-
e.height(),e.height(f));i.each(function(a){var h=parseInt(b(this).css("padding-left"),10)||0,h=h+(parseInt(b(this).css("padding-right"),10)||0),c=parseInt(b(this).css("padding-top"),10)||0,c=c+(parseInt(b(this).css("padding-bottom"),10)||0);b(this).css({left:a*q,width:q-h,minHeight:f-c})});j.moveToPage(k,!1)}function M(a){a.preventDefault();var h=N(a),c=h.x-l[l.length-1].position.x,b=h.y-l[l.length-1].position.y;if(!t&&(Math.abs(c)>d.minTrackForDrag||Math.abs(b)>d.minTrackForDrag))E=t=!0;if(t)if(a.stopPropagation(),
E)E=!1,y=!!(1<r&&Math.abs(c)>Math.abs(b)),A=h,y?(B(!1),o.fadeOut(d.scrollbarFadeDuration)):o.fadeIn(d.scrollbarFadeDuration);else{A=h;if(y){var b=-1*(r-1)*q,e=s(p).left,b=Math.min(Math.max(e+c,b),0);C(p,b,0,!1)}else{e=i.eq(k);c=s(e).top;e=f-e.outerHeight();c+=b;if(d.bounce){if(c<e||0<c)c-=b/2}else c=Math.min(Math.max(c,e),0);j.scrollTo(-c,!1)}l.push({timeStamp:a.timeStamp,position:h})}}function F(a){b(document).unbind(O,M);b(document).unbind(P,F);b(document).unbind("touchcancelled",Q);document.addEventListener&&
e[0].removeEventListener("click",R,!0);if(document.addEventListener&&!t){for(var h=S;1!=h.nodeType;)h=h.parentNode;b(h).trigger("focus");if(u){var c=a.originalEvent,m=document.createEvent("MouseEvents");m.initMouseEvent("click",!0,!0,c.view,1,c.changedTouches?c.changedTouches[0].screenX:c.screenX,c.changedTouches?c.changedTouches[0].screenY:c.screenY,c.changedTouches?c.changedTouches[0].clientX:c.clientX,c.changedTouches?c.changedTouches[0].clientY:c.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,
0,null);h.dispatchEvent(m)}}if(t){a.stopPropagation();for(t=!1;0<l.length&&!(a.timeStamp-l[0].timeStamp<=d.maxTimeTrackingData);)l.shift();1<l.length&&(a=l[0],h=l[l.length-1],g=(y?h.position.x-a.position.x:h.position.y-a.position.y)/(h.timeStamp-a.timeStamp),g*=d.animFrameRate,y?Math.abs(g)>d.minVelocityForPaging&&(v=!0,0<g?j.prevPage(!0):j.nextPage(!0)):d.decelerate&&Math.abs(g)>d.minVelocityForDeceleration&&(v=!0,T=setInterval(Y,d.animFrameRate)))}v||(B(!0),o.fadeOut(d.scrollbarFadeDuration))}function R(a){a.preventDefault();
a.stopPropagation()}function Q(a){F(a)}function U(){q=e.width();f=e.height();i.css({minHeight:f});L()}function Z(a,b){a.preventDefault();var c=i.eq(k),d=3*parseInt(c.css("line-height"),10)||50;0>b&&(d*=-1);G();var e=s(c);C(c,e.left+0,e.top+d,!1);B(!1)}function H(){v=!1;o.fadeOut(d.scrollbarFadeDuration)}function Y(){if(v){var a=i.eq(k),b=s(a).top,b=b+g;if(!d.bounce&&(b<f-a.outerHeight()||0<b))b=Math.min(Math.max(b,f-a.outerHeight()),0),g=0;j.scrollTo(-b,!1);g*=d.friction;if(Math.abs(g)<d.minVelocity)o.fadeOut(d.scrollbarFadeDuration),
g=0,G(),B(!0);else if(d.bounce&&(b<f-a.outerHeight()||0<b))g*=0.5}}function G(){clearInterval(T);v=!1;u?(p.css({webkitTransitionDuration:0}),i.css({webkitTransitionDuration:0})):(p.stop(),i.stop())}function B(a){var b=s(p).left,b=-1*Math.round(b/q);j.moveToPage(b,a);var c=i.eq(k),b=s(c).top,c=Math.min(Math.max(b,f-c.outerHeight()),0);b!=c?(c*=-1,o.hide(),j.scrollTo(c,a)):o.fadeOut(d.scrollbarFadeDuration)}function N(a){a=a.originalEvent.touches&&0<a.originalEvent.touches.length?a.originalEvent.touches[0]:
a;return{x:a.pageX,y:a.pageY}}function C(a,b,c,e){var f=s(a);f.left==b&&f.top==c||(u?a.css({webkitTransitionDuration:e?d.transitionDuration:"0",webkitTransform:"translate3d("+b+"px,"+c+"px,0px)"}):(a.stop(),e?a.animate({left:b,top:c},d.transitionDuration,"swing",H):a.css({left:b,top:c})))}function s(a){return u?(a=new WebKitCSSMatrix(window.getComputedStyle(b(a)[0]).webkitTransform),{left:a.e,top:a.f}):b(a).position()}function I(a){"string"==typeof a&&0<a.length?(a=a.replace("##index##",k),eval(a)):
b.isFunction(a)&&a.call(i.eq(k),k)}var j=this,e=b(n),p=null,i=null,w=null,J=null,D=null,o=null,q=0,f=0,r=0,k=0,x=!!("ontouchstart"in window),u=!!("iPhone"==navigator.platform||"iPad"==navigator.platform||"iPod"==navigator.platform),y=!1,t=!1,E=!1,v=!1,T=0,g=0,l=[],A={x:0,y:0},z=0,K=!1,S=null,$=x?"touchstart":"mousedown",O=x?"touchmove":"mousemove",P=x?"touchend":"mouseup",d=b.extend({},b.dmxSlidePanelDefaults,X);b.extend(j,{version:"1.0.8",currentPage:function(){return k},totalPages:function(){return r},
prevPage:function(a){j.moveToPage(k-1,a)},nextPage:function(a){j.moveToPage(k+1,a)},moveToPage:function(a,e){if("string"==typeof a)for(var a=a.replace("#",""),c=0;c<i.length;++c)if(i.eq(c).attr("id")==a){a=c;break}isNaN(a)||(a=Math.min(Math.max(a,0),r-1),k!=a&&(I(d.onPageHide),k=a,I(d.onPageShow)),b(d.currentPageText).text(k+1),w.each(function(){b("a",this).removeClass("selected").eq(k).addClass("selected");var a=b("ul",this);a.css("position")=="relative"&&a.css("overflow-x")=="auto"&&a.stop().animate({scrollLeft:a[0].scrollLeft+
b("a.selected",this).position().left},200)}),D.removeClass("disabled"),J.removeClass("disabled"),0==a?D.addClass("disabled"):a==r-1&&J.addClass("disabled"),C(p,-1*a*q,0,e))},scrollTo:function(a,e){var c=i.eq(k);if("string"==typeof a)for(var a=a.replace("#",""),m=b("a",p),l=0;l<m.length;++l){var g=m.eq(l);if(g.attr("name")==a){c=g.closest("."+d.pageClass);m=c.outerHeight()-f;j.moveToPage(i.index(c),e);a=Math.min(Math.max(g.position().top,0),m);break}}isNaN(a)||(m=f/c.outerHeight(),g=m*a,m*=f-10,0>
a?(m=Math.max(5,m+g),g=5):a>c.outerHeight()-f&&(m=Math.max(5,f-g-5)),o.css({top:g,height:m}),g=s(c).left,C(c,u?0:g,-1*a,e))},play:function(){0==z&&(z=setInterval(function(){k==r-1?K=!0:0==k&&(K=!1);K?j.prevPage(!0):j.nextPage(!0)},d.autoPlayInterval))},stop:function(){0!=z&&(clearInterval(z),z=0)}});"string"==typeof d.friction&&(d.friction=V[d.friction]);"string"==typeof d.transitionDuration&&(d.transitionDuration=W[d.transitionDuration]);d.friction=Math.min(Math.max(d.friction,0),1);d.transitionDuration+=
u?"ms":"";p=e.wrapInner("<div></div>").find("> div");i=p.children().addClass(d.pageClass);o=b('<div class="'+d.scrollbarClass+'"></div>').appendTo(e);r=i.length;b(d.totalPagesText).text(r);w=e.parent().find(d.pageNavigation);D=b(d.prevPage+" a");J=b(d.nextPage+" a");0==w.length&&(w=b(d.pageNavigation));w.each(function(){b("a",this).eq(0).addClass("selected")});D.addClass("disabled");b.each(["padding-top","padding-right","padding-bottom","padding-left"],function(a,d){var c=parseInt(e.css(d),10)||0;
c>0&&i.each(function(){pageValue=parseInt(b(this).css(d),10)||0;b(this).css(d,pageValue+c)})});q=e.width();f=e.height();e.css({position:"static"==e.css("position")?"relative":e.css("position"),overflow:"hidden",padding:0});p.css({position:"absolute",left:0,top:0,margin:0,padding:0});i.css({position:"absolute",overflow:"hidden",left:0,top:0,width:q,height:"auto",minHeight:f});o.css({position:"absolute",right:5,top:5,width:5,height:150,padding:0,margin:0}).hide();u&&(x={webkitTransitionProperty:"-webkit-transform",
webkitTransitionDuration:0,webkitTransform:"translate3d(0px,0px,0px)"},p.css(x).bind("webkitTransitionEnd",H),i.css(x).bind("webkitTransitionEnd",H),o.css({webkitTransitionProperty:"opacity",webkitTransitionDuration:200}));L();b(window).bind("resize",U);b(window).bind("orientationchange",U);e.bind($,function(a){if(!(b.inArray(a.target.tagName.toLowerCase(),d.ignoreDragOn)>-1)){a.preventDefault();document.addEventListener&&e[0].addEventListener("click",R,true);S=a.target;G();A=N(a);l=[];l.push({timeStamp:a.timeStamp,
position:A});t=false;b(document).bind(O,M);b(document).bind(P,F);b(document).bind("touchcancelled",Q)}});d.mousewheel&&e.mousewheel&&e.mousewheel(Z);b(d.prevPage).click(function(a){a.preventDefault();j.prevPage(true)});b(d.nextPage).click(function(a){a.preventDefault();j.nextPage(true)});w.each(function(){b("a",this).each(function(a){b(this).bind("click",{page:a},function(a){a.preventDefault();j.moveToPage(a.data.page,true)})})});window.location.hash&&j.moveToPage(window.location.hash,!1);d.autoPlay&&
j.play();I(d.onPageShow)};b.dmxSlidePanelDefaults={autoHeight:!0,autoPlay:!1,autoPlayInterval:5E3,bounce:!0,decelerate:!0,friction:0.95,maxTimeTrackingData:100,animFrameRate:1E3/60,minVelocity:0.05,minVelocityForDeceleration:1,minVelocityForPaging:5,minTrackForDrag:5,transitionDuration:250,mousewheel:!0,ignoreDragOn:["input","select","textarea","button"],pageClass:"dmxSlidingPanelsPage",pageNavigation:".dmxSlidingPanelsNav",currentPageText:".dmxSlidingPanelsCurrentPage",totalPagesText:".dmxSlidingPanelsTotalPages",
prevPage:".dmxSlidingPanelsPrev",nextPage:".dmxSlidingPanelsNext",scrollbarClass:"dmxSlidingPanelsScrollbar",scrollbarFadeDuration:200,onPageShow:null,onPageHide:null}})(jQuery);
